<section class='login'>
<?php
$form = $this->form;
$form->prepare();
// ddd($this->url(NULL, array('controller'=>'Login', 'action'=>'process')));
$form->setAttribute('action', $this->url(NULL, array('controller'=>'Login', 'action'=>'process')));
$form->setAttribute('method','post');
echo $this->form()->openTag($form);
?>
<dl class="login-form">
<dt><?php echo $this->formLabel($form->get('email')); ?></dt>
<dd><?php
	echo $this->formElement($form->get('email'));
	echo $this->formElementErrors($form->get('email'));
?></dd>
<dt><?php echo $this->formLabel($form->get('password'))?></dt>
<dd><?php
  echo $this->formElement($form->get('password'));
  echo $this->formElementErrors($form->get('password'));
 ?></dd>
 <dd>
 	<?php echo $this->formElement($form->get('submit'));?>
 </dd>
</dl>
<?php
echo $this->form()->closeTag($form);?>
</section>
